steps:
  # Receive files from bucket
  - id: 'Receive files from bucket'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
    - 'cp'
    - '-r'
    - 'gs://${PROJECT_ID}_cloudbuild/deps/root/.ssh'
    - '/root/'
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  # Decrypt the file containing the key
  - id: 'Decrypt the file containing the key'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
    - kms
    - decrypt
    - --ciphertext-file=/root/.ssh/id_rsa.enc
    - --plaintext-file=/root/.ssh/id_rsa
    - --location=global
    - --keyring=projects/${PROJECT_ID}/locations/global/keyRings/cloudbuild-github-keyring
    - --key=projects/${PROJECT_ID}/locations/global/keyRings/cloudbuild-github-keyring/cryptoKeys/github-key
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  # Set up git with key and domain.
  - id: 'Set up git with key and domain'
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      chmod 600 /root/.ssh/id_rsa
      cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_rsa
      EOF
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  # Connect to the repository
  - id: 'Pull code from repository'
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone git@github.com:vrert/$REPO_NAME
        cd $REPO_NAME
        git checkout ${TAG_NAME}
        git submodule init
        git submodule update
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - id: 'Push tags to repository'
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd $REPO_NAME
        git tag $(echo ${TAG_NAME} | cut -d'_' -f 1)_${_NEW_TAG} $(git rev-parse HEAD)
        git push git@github.com:vrert/$REPO_NAME $(echo ${TAG_NAME} | cut -d'_' -f 1)_${_NEW_TAG}
    volumes:
      - name: 'ssh'
        path: /root/.ssh
